FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

#instalar o ts-node-dev globalmente?
#RUN npm install -g ts-node-dev

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
