services:
  api:
    build:
      context: ./backend/api
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - ./backend/api/.env.api
    volumes:
      - ./backend/api:/app
      - /app/node_modules
    networks:
      - network
    depends_on:
      - database

  database:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - ./backend/.env.db
    volumes:
      - database:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - network

  frontend:
    build:
      context: ./frontend/vite-react-app
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
      - NODE_ENV=development
    restart: unless-stopped
    volumes:
      - ./frontend/vite-react-app:/app
      - /app/node_modules
    networks:
      - network
    depends_on:
      - api

networks:
  network:
    driver: bridge

volumes:
  database:
