services:
  api:
    build:
      context: ./backend/api
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - ./backend/api/.env.api
    volumes:
      - ./backend/api:/app
      - /app/node_modules
    networks:
      - network
    depends_on:
      - database

  database:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file:
      - ./backend/.env.db
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - network

  frontend:
    build:
      context: ./frontend/vite
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/vite:/app
      - /app/node_modules
    networks:
      - network
    depends_on:
      - api

networks:
  network:
    driver: bridge

volumes:
  database:
